from Student_Scholarship_Portal import db
from flask_login import UserMixin

class Applicant(db.Model):
    id = db.Column(db.Integer(), primary_key = True)
    name = db.Column(db.String(30), nullable = False)
    DOB = db.Column(db.String(10), nullable = False)
    gender = db.Column(db.String(10), nullable = False)
    category = db.Column(db.String(10), nullable = False)
    USN = db.Column(db.String(15), nullable = False)
    email = db.Column(db.String(50), nullable = False)
    phone = db.Column(db.String(10), nullable = False)
    income = db.Column(db.Integer(), nullable = False)
    identity_proof_filename = db.Column(db.String(50), nullable = False)
    identity_proof_data = db.Column(db.LargeBinary, nullable = False)
    income_certificate_filename = db.Column(db.String(50), nullable = False)
    income_certificate_data = db.Column(db.LargeBinary, nullable = False)
    address = db.Column(db.String(100), nullable = False)
    pin = db.Column(db.Integer(), nullable = False)
    area = db.Column(db.String(50), nullable = False)
    district = db.Column(db.String(50), nullable = False)
    state = db.Column(db.String(30), nullable = False)
    address_proof_filename = db.Column(db.String(50), nullable = False)
    address_proof_data = db.Column(db.LargeBinary, nullable = False)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    bank_id = db.Column(db.Integer(), db.ForeignKey('bank.id'))
    current_education_id = db.Column(db.Integer(), db.ForeignKey('current_education.id'))
    education_id = db.Column(db.Integer(), db.ForeignKey('education.id'))
    scholarship_id = db.Column(db.Integer(), db.ForeignKey('scholarship.id'))

class Bank(db.Model):
    id = db.Column(db.Integer(), primary_key = True)
    accNo = db.Column(db.String(15), nullable = False)
    IFSC = db.Column(db.String(15), nullable = False)
    bName = db.Column(db.String(30), nullable = False)
    branch = db.Column(db.String(30), nullable = False)
    accName = db.Column(db.String(30), nullable = False)
    passbook_filename = db.Column(db.String(50), nullable = False)
    passbook_data = db.Column(db.LargeBinary, nullable = False)

class Current_education(db.Model):
    id = db.Column(db.Integer(), primary_key = True)
    cLevel = db.Column(db.String(30), nullable = False)
    cName = db.Column(db.String(30), nullable = False)
    clgName = db.Column(db.String(100), nullable = False)
    cState = db.Column(db.String(30), nullable = False)
    tFee = db.Column(db.Integer(), nullable = False)
    ntFee = db.Column(db.Integer(), nullable = False)
    fee_receipt_filename = db.Column(db.String(50), nullable = False)
    fee_receipt_data = db.Column(db.LargeBinary, nullable = False)
    admission_letter_filename = db.Column(db.String(50), nullable = False)
    admission_letter_data = db.Column(db.LargeBinary, nullable = False)

class Education(db.Model):
    id = db.Column(db.Integer(), primary_key = True)
    name10 = db.Column(db.String(100), nullable = False)
    state10 = db.Column(db.String(30), nullable = False)
    pass10 = db.Column(db.String(10), nullable = False)
    per10 = db.Column(db.String(5), nullable = False)
    marksheet10_filename = db.Column(db.String(50), nullable = False)
    marksheet10_data = db.Column(db.LargeBinary, nullable = False)
    name12 = db.Column(db.String(100), nullable = False)
    state12 = db.Column(db.String(30), nullable = False)
    pass12 = db.Column(db.String(10), nullable = False)
    per12 = db.Column(db.String(5), nullable = False)
    marksheet12_filename = db.Column(db.String(50), nullable = False)
    marksheet12_data = db.Column(db.LargeBinary, nullable = False)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key = True)
    name = db.Column(db.String(30), nullable = False)
    phone = db.Column(db.String(10), nullable = False)
    admin_access  = db.Column(db.Boolean, default = False)
    email = db.Column(db.String(50), nullable = False, unique = True)
    password = db.Column(db.String(60), nullable = False)
    application = db.relationship('Applicant')

class Scholarship(db.Model):
    id = db.Column(db.Integer(), primary_key = True)
    sName = db.Column(db.String(200), nullable = False)
    abt_programme = db.Column(db.String(1000), nullable = False)
    eligibility = db.Column(db.String(1000), nullable = False)
    documents_required = db.Column(db.String(1000), nullable = False)
    benefits = db.Column(db.String(30), nullable = False)
    deadline = db.Column(db.String(10), nullable = False)
    applicant = db.relationship('Applicant')

class Queries(db.Model):
    id = db.Column(db.Integer(), primary_key = True)
    name = db.Column(db.String(30), nullable = False)
    email = db.Column(db.String(50), nullable = False)
    subject = db.Column(db.String(200), nullable = False)
    message = db.Column(db.String(2000), nullable = False)
